### ISSUE TITLE
encrypt_data review

### ISSUE THREAD

**Issue by jsalamander** [elias-summermatter/sspliter#3]
For key in keys..
https://github.com/elias-summermatter/sspliter/blob/dac04b4da8bbc11e29577092da352b7f52b6fbf3/ssplit.py#L206

Why is it 32? and why does it just continue then?
https://github.com/elias-summermatter/sspliter/blob/dac04b4da8bbc11e29577092da352b7f52b6fbf3/ssplit.py#L207

**Comment by elias-summermatter** [comment]
Because AES256 needs keys of length 32 Byte or 256Bit ;-) Bit strength of  AES is determined by the length of the key. This condition should prevent encryption that is less strong than 256bit  ;-)
